# 1. Использование команд библиотеки NumPy

* 1.1. Создайте одномерный массив my_array, в котором по порядку все числа до 100,
кратные 5

In [24]:
import numpy as np

my_array = np.arange(5, 101, 5)
print(my_array)

[  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100]


*  2.1. Из полученного массива получить массив с кратными 10 числами

In [25]:
# Выполняем операцию фильтрации
new10_array = my_array[my_array % 10 == 0]
print(new10_array)

[ 10  20  30  40  50  60  70  80  90 100]


* 3.1 Получить двумерный массив с двумя столбцами

In [26]:
# Преобразование в двумерный массив с двумя столбцами
new2st_array = new10_array.reshape(-1, 2)
print(new2st_array)

[[ 10  20]
 [ 30  40]
 [ 50  60]
 [ 70  80]
 [ 90 100]]


* 4.1 Получите набор my_second_array, в котором все элементы меньше предыдущего исходного на 5

In [27]:
my_second_array = new2st_array - 5
print(my_second_array)

[[ 5 15]
 [25 35]
 [45 55]
 [65 75]
 [85 95]]


* 5.1 Соедините массивы, полученные в п. 3.1 и 4.1, горизонтально. Используйте .T для транспонирования матрицы.


In [28]:
combined_array = (np.hstack((new2st_array, my_second_array),dtype=float))
print(combined_array)

[[ 10.  20.   5.  15.]
 [ 30.  40.  25.  35.]
 [ 50.  60.  45.  55.]
 [ 70.  80.  65.  75.]
 [ 90. 100.  85.  95.]]


* 6.1 Разделите 2 и 3 строку на 4 верхних строки my_array. Используйте .T для транспонирования матрицы


In [29]:
combined_array.T[1]=(combined_array.T[1]/new2st_array.T[0]).reshape(-1,5)
combined_array.T[2]=(combined_array.T[2]/new2st_array.T[1]).reshape(-1,5)
print(combined_array.T)

[[10.         30.         50.         70.         90.        ]
 [ 2.          1.33333333  1.2         1.14285714  1.11111111]
 [ 0.25        0.625       0.75        0.8125      0.85      ]
 [15.         35.         55.         75.         95.        ]]


* 7.1 Оставить только те значения, которые не изменились после деления

In [30]:
no_changed_values = np.delete(combined_array.T, [1,2], axis=0)
print(no_changed_values)

[[10. 30. 50. 70. 90.]
 [15. 35. 55. 75. 95.]]


* 8.1 Снова получить трехстрочный двумерный массив и поменять местами первую и третью строки


In [31]:
new3_row_array = my_second_array[:3, :]
print("Original three row array:\n", new3_row_array)
new3_row_array[[0, 2]] = new3_row_array[[2, 0]]
print("Transposed three row array after swapping places:\n", new3_row_array)

Original three row array:
 [[ 5 15]
 [25 35]
 [45 55]]
Transposed three row array after swapping places:
 [[45 55]
 [25 35]
 [ 5 15]]


* 9.1 Получить среднее, медиану и стандартное отклонение для каждой строки, используя команды np.mean(), np.median(), np.std().


In [32]:
deviation_mean = np.mean(new3_row_array, axis=1)
print("Mean deviation per row: \n", deviation_mean)
deviation_median = np.median(new3_row_array, axis=1)
print("Median deviation per row: \n", deviation_median)
standard_deviation = np.std(new3_row_array, axis=1)
print("Standard deviation per row: \n", standard_deviation)

Mean deviation per row: 
 [50. 30. 10.]
Median deviation per row: 
 [50. 30. 10.]
Standard deviation per row: 
 [5. 5. 5.]


* 10.1 Сделать нормализацию на максимальное значение вдоль строк, поделив каждый элемент массива на max() вдоль строк.


In [33]:
# Используем np.divide для нормализации
normalized_array = np.divide(new3_row_array, new3_row_array.max(axis=1, keepdims=True))
print("Normalized array:\n", normalized_array)

Normalized array:
 [[0.81818182 1.        ]
 [0.71428571 1.        ]
 [0.33333333 1.        ]]


# 2. Использование команд библиотеки pandas

* 2.1 Импортируйте данные из файла “Global Population Trends(2016-2022).csv”. Описание данных смотрите ниже.

In [34]:
import pandas as pd
global_trends_data= pd.read_csv('trends.csv')

* 2.3 Считайте несколько первых записей таблицы (head())


In [35]:
global_trends_data.head()

Country  Year Total Population Urban Population Rural Population  \
0  Afghanistan  2017                -                -                -   
1  Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2  Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3  Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4  Afghanistan  2021       40,099,462       10,551,772       29,547,690   

  Population Density Life Expectancy  Birth Rate  Death Rate Fertility Rate  \
0                 55            63.0      37.342       7.027          5.129   
1                 56            63.0      36.927       6.981          5.002   
2                 58            64.0      36.466       6.791           4.87   
3                 60            63.0      36.051       7.113           4.75   
4                  -            62.0      35.842       7.344          4.643   

  Infant Mortality Rate Growth Rate  
0                  49.4           -  
1                  47.8         3.0  
2                  46.3         3.0  
3                  44.8         3.0  
4                  43.4         3.0

* 2.3 Определите размерность данного фрейма (shape())


In [36]:
global_trends_data.shape

(1073, 12)

* 2.4 Выведите название заголовков столбцов фрейма (columns)

In [37]:
global_trends_data.columns

Index(['Country', 'Year', 'Total Population', 'Urban Population',
       'Rural Population', 'Population Density', 'Life Expectancy',
       'Birth Rate', 'Death Rate', 'Fertility Rate', 'Infant Mortality Rate',
       'Growth Rate'],
      dtype='object')

* 2.5 Получите описание всех переменных (полей) (info())


In [38]:
global_trends_data.info

<bound method DataFrame.info of           Country  Year Total Population Urban Population Rural Population  \
0     Afghanistan  2017                -                -                -   
1     Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2     Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3     Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4     Afghanistan  2021       40,099,462       10,551,772       29,547,690   
...           ...   ...              ...              ...              ...   
1068     Zimbabwe  2017                -                -                -   
1069     Zimbabwe  2018       15,052,184        4,848,158       10,204,026   
1070     Zimbabwe  2019       15,354,608        4,945,719       10,408,889   
1071     Zimbabwe  2020       15,669,666        5,052,214       10,617,452   
1072     Zimbabwe  2021       15,993,524        5,166,388       10,827,136   

     Population Density Life Ex

* 2.6  Удалите строки, не содержащие значения в столбце «Total Population» - “-”

In [39]:
df=global_trends_data[global_trends_data['Total Population']!='-']
df

Country  Year Total Population Urban Population Rural Population  \
1     Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2     Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3     Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4     Afghanistan  2021       40,099,462       10,551,772       29,547,690   
6         Albania  2018        2,866,376        1,728,969        1,137,407   
...           ...   ...              ...              ...              ...   
1067       Zambia  2021       19,473,125        8,800,295       10,672,830   
1069     Zimbabwe  2018       15,052,184        4,848,158       10,204,026   
1070     Zimbabwe  2019       15,354,608        4,945,719       10,408,889   
1071     Zimbabwe  2020       15,669,666        5,052,214       10,617,452   
1072     Zimbabwe  2021       15,993,524        5,166,388       10,827,136   

     Population Density Life Expectancy  Birth Rate  Death Rate  \
1                    56            63.0      36.927       6.981   
2                    58            64.0      36.466       6.791   
3                    60            63.0      36.051       7.113   
4                     -            62.0      35.842       7.344   
6                   105            79.0      10.517       8.308   
...                 ...             ...         ...         ...   
1067                  -            61.0      34.511       6.973   
1069                 39            61.0      32.074       7.972   
1070                 40            61.0      31.518       8.043   
1071                 41            61.0      31.009       8.132   
1072                  -            59.0      30.537       9.057   

     Fertility Rate Infant Mortality Rate Growth Rate  
1             5.002                  47.8         3.0  
2              4.87                  46.3         3.0  
3              4.75                  44.8         3.0  
4             4.643                  43.4         3.0  
6              1.44                   8.3         0.0  
...             ...                   ...         ...  
1067          4.308                  40.2         3.0  
1069          3.659                  38.0         2.0  
1070          3.599                  37.1         2.0  
1071          3.545                  36.6         2.0  
1072          3.491                  35.7         2.0  

[864 rows x 12 columns]

* 2.7 Получите описательную статистику по переменным (например, max(), min(), describe())


In [40]:
global_trends_data.max()


Country                    Zimbabwe
Year                           2021
Total Population             99,258
Urban Population         99,876,265
Rural Population            998,397
Population Density               99
Life Expectancy                85.0
Birth Rate                   46.351
Death Rate                     21.7
Fertility Rate                7.084
Infant Mortality Rate           9.9
Growth Rate                     5.0
dtype: object

In [41]:
global_trends_data.min()

Country                  Afghanistan
Year                            2017
Total Population                   -
Urban Population                   -
Rural Population                   -
Population Density                 -
Life Expectancy                    -
Birth Rate                       0.0
Death Rate                       0.0
Fertility Rate                     -
Infant Mortality Rate              -
Growth Rate                        -
dtype: object

In [42]:
global_trends_data.describe()

Year   Birth Rate   Death Rate
count  1073.000000  1073.000000  1073.000000
mean   2019.013048    18.801519     7.841907
std       1.410190     9.903449     2.973418
min    2017.000000     0.000000     0.000000
25%    2018.000000    10.620000     6.067000
50%    2019.000000    16.025000     7.396000
75%    2020.000000    25.921000     9.313000
max    2021.000000    46.351000    21.700000

* 2.8 Выполните сортировку данных по нескольким критериям


In [43]:
sorted_data = global_trends_data.sort_values(by=['Birth Rate','Total Population'], ascending=True) # Сортировка сначала по столбцу 'Birth Rate' (Уровень рождаемости), а затем по столбцу 'Total Population' (Общая численность населения) в порядке возрастания.
sorted_data

Country  Year Total Population Urban Population Rural Population  \
629          Monaco  2021           36,686           36,686                -   
628          Monaco  2020           36,922           36,922                -   
627          Monaco  2019           37,034           37,034                -   
18   American Samoa  2021           45,035           39,257            5,778   
16   American Samoa  2019           47,321           41,239            6,082   
..              ...   ...              ...              ...              ...   
863         Somalia  2017                -                -                -   
693           Niger  2020       24,333,639        4,045,711       20,287,928   
692           Niger  2019       23,443,393        3,872,145       19,571,248   
691           Niger  2018       22,577,058        3,708,282       18,868,776   
690           Niger  2017                -                -                -   

    Population Density Life Expectancy  Birth Rate  Death Rate Fertility Rate  \
629                  -               -       0.000       0.000              -   
628             18,215               -       0.000       0.000              -   
627             18,270               -       0.000       0.000              -   
18                   -               -       0.000       0.000              -   
16                 237               -       0.000       0.000              -   
..                 ...             ...         ...         ...            ...   
863                 24            56.0      45.457      11.891          6.738   
693                 19            61.0      45.588       8.281          6.892   
692                 19            63.0      45.859       7.824          6.961   
691                 18            62.0      46.127       8.061          7.023   
690                 17            62.0      46.351       8.239          7.084   

    Infant Mortality Rate Growth Rate  
629                   1.0        -1.0  
628                   1.0         0.0  
627                   1.0         0.0  
18                      -        -3.0  
16                      -        -2.0  
..                    ...         ...  
863                  79.1           -  
693                  59.9         4.0  
692                  60.2         4.0  
691                  60.4         4.0  
690                  60.6           -  

[1073 rows x 12 columns]

* 2.9 Выведите название страны, которая имеет максимальную численность населения


In [44]:
population_max = global_trends_data['Total Population'].idxmax()
population_max_res = global_trends_data.loc[population_max, 'Country']
print(population_max_res + " is a country with maximum population")

Seychelles is a country with maximum population


* 2.10 Выведите название страны, которая имеет минимальную численность населения


In [45]:
population_min = global_trends_data['Total Population'].idxmin()
population_min_res = global_trends_data.loc[population_min, 'Country']
print(population_min_res + " is a country with minimal population")

Afghanistan is a country with minimal population


* 2.11 Экспорт фрейма в MS Excel


In [46]:
global_trends_data.to_excel("new_trend_file.xlsx", index=False)